language: node_js

node_js:
  - lts/*

cache: npm

script: 
  - cd frontend
  - npm install
  - npm 
  # Commented out due to MongoDB altas cluster being disabled.
  # - cd ../backend
  # - npm install
  # - npm test